### ISSUE TITLE
ifconfig-parser is not able to parse data with attribute SLAVE

### ISSUE THREAD

**Issue by devrajpaul** [ssudake21/ifconfig-parser#10]
ifconfig data:
Link encap:Ethernet  HWaddr 3c:fd:fe:b9:2f:10
UP BROADCAST RUNNING SLAVE MULTICAST  MTU:9100  Metric:1

This can be resolved by adding the attribute SLAVE to
_flag_list = (
        'BROADCAST', 'MULTICAST', 'UP', 'RUNNING', 'LOOPBACK', 'DYNAMIC',
        'PROMISC', 'NOARP', 'POINTOPOINT', 'SIMPLEX', 'SMART', 'MASTER', 
        'SLAVE'
    )

Error:
File "/Users/xxxx/.venv/xxxxx/lib/python2.7/site-packages/ifparser/ifconfig.py", line 44, in __setattr__
    (name, value))
ValueError: Invalid attribute mentioned name=SLAVE value=True

**Comment by trevormccasland** [comment]
enp135s0f0 Link encap:Ethernet  HWaddr 3c:fd:fe:b9:2f:10
          UP BROADCAST RUNNING SLAVE MULTICAST  MTU:9100  Metric:1
          RX packets:83506277 errors:0 dropped:0 overruns:0 frame:0
          TX packets:40450344 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:47759052436 (47.7 GB)  TX bytes:21148910170 (21.1 GB)
