### ISSUE TITLE
Fork with bug fixes and enhancements

### ISSUE THREAD

**Issue by mwfong-csl** [ssudake21/ifconfig-parser#6]
I've created a new fork with bug fixes and enhancements: [https://github.com/mwfong-csl/ifconfig-parser](url). See its commit history for more info.

**Comment by mwfong-csl** [comment]
Is the best course of action to make a pull request to initiate code review and evaluation?

**Comment by ssudake21** [comment]
Sure .Please raise pull request. I missed to take look at this.
