### ISSUE TITLE
ifconfig-parser is not able to parse vlan data

### ISSUE THREAD

**Issue by devrajpaul** [ssudake21/ifconfig-parser#9]
The ifconfig-parser is not able to parse data if the vlan has a dot in the interface name, for example interface name = bond1.35
Python: 2.7.15
Error:

 File "/Users/xxxxxxx/.venv/xxxxxx/lib/python2.7/site-packages/ifparser/ifconfig.py", line 87, in __init__
    self._process(raw_text)
  File "/Users/xxxxxx/.venv/xxxxx/lib/python2.7/site-packages/ifparser/ifconfig.py", line 97, in _process
    raise ParseError(repr(line))
ParseError: 'bond1.35  Link encap:Ethernet  HWaddr 3c:fd:fe:b9:2f:10'

**Comment by trevormccasland** [comment]
I believe this issue is already resolved with the commit [1]. 

@ssudake21 do you mind creating a release so that we can install the latest support for these interfaces?

[1] https://github.com/ssudake21/ifconfig-parser/commit/93674e4b19f949cbe3da804957a5d31d5fd697e7

**Comment by ssudake21** [comment]
@trevormccasland  Updated ifparser to 0.8.0 in PYPI. Can you check if helps ?

**Comment by trevormccasland** [comment]
@ssudake21 Yes this helps. Thank you so much for your timely response on this issue.

# pip show ifparser
ubuntu@ubuntu:~$ pip show ifparser
Name: ifparser
Version: 0.8.0
Summary: Parse ifconfig output and retrieve values with goodies
Home-page: http://github.com/ssudake21/ifconfig-parser
Author: Sanket Sudake
Author-email: sanketsudake@gmail.com
License: BSD
Location: /usr/local/lib/python2.7/dist-packages

# Python interpreter output below

>>> obj = ifconfig.Ifcfg('bond1.35 Link encap:Ethernet HWaddr 3c:fd:fe:b9:2f:10')
>>> bond = obj.get_interface('bond1.35')
>>> bond.get_values()
{u'itype': 'Ethernet HWaddr 3c', u'ip': None, u'UP': False, u'interface': 'bond1.35', u'MULTICAST': False, u'rxpkts': None, u'bcast': None, u'txdroppedpkts': None, u'NOARP': False, u'txoverruns': None, u'rxoverruns': None, u'LOOPBACK': False, u'POINTOPOINT': False, u'DYNAMIC': False, u'PROMISC': False, u'txpkts': None, u'BROADCAST': False, u'txbytes': None, u'rxbytes': None, u'MASTER': False, u'rxframe': None, u'txcarrier': None, u'hwaddr': None, u'SMART': False, u'rxerrors': None, u'mask': None, u'rxdroppedpkts': None, u'mtu': None, u'txerrors': None, u'RUNNING': False, u'SIMPLEX': False}

**Comment by ssudake21** [comment]
Cool. Closing issue.
